### ISSUE TITLE
Create your first Hacktoberfest 2020 Pull Request here.

### ISSUE THREAD

**Issue by iamvpa** [iamvpa/PRpractice#18]
Welcome, If you are a beginner and are struggling with open source contribution then you are in the right place. 
Just add your name and city in README.md with the following format:
"### <<your name>your name> from <<city>city>"
Fork and star the repository to get started. A follow would be nice.

**Comment by tdserapio** [comment]
Oh, this will be my 2nd PR. But Thanks.

**Comment by aortiz24** [comment]
@iamvpa, Can I do this? This is my first time at Hacktoberfest!

**Comment by iamvpa** [comment]
Sure...everyone is welcome. You do not have to ask, just send a PR and that's it !

**Comment by shradhaagarwal01** [comment]
Does adding/updating README.md counts?

**Comment by iamvpa** [comment]
Sure..go ahead !
